<?php

/**
 * @file
 * Zoho CRM module hooks.
 */

/**
 * Implements hook_theme().
 */
function zoho_crm_integration_theme($existing, $type, $theme, $path) {
  return [
    'zoho_crm_integration__settings_page' => [
      'variables' => [
        'form' => NULL,
        'status' => NULL,
        'has_client_id' => FALSE,
        'auth_url' => NULL,
        'revoke_url' => NULL,
      ],
    ],
  ];
}
